GET http://localhost:5171/games

###
GET http://localhost:5171/games/3

###
POST http://localhost:5171/games
Content-Type: application/json

{
    "name": "F1 Race Stars",
    "genre": "Racing",
    "price": 59.99,
    "releasedate": "2023-10-01"
}

###
PUT http://localhost:5171/games/1
Content-Type: application/json

{
    "id": 1,
    "name": "F1 Race Stars",
    "genre": "Racing",
    "price": 19.99,
    "releasedate": "2023-01-15"
}


###
DELETE http://localhost:5171/games/1

